config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resources :photos, only: [ :show, :destroy ]
  end

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post
  validates :cloud_id, presence: true

  mount_uploader :cloud_id, PhotoUploader
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true

  has_many :photos, dependent: :destroy

  #esta linha permite criar photos ao mesmo tempo que crio posts
  #allows us to add "photo model fields in Post's model view"
  accepts_nested_attributes_for :photos, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController

  def index
    @photo = Photo.all
  end

  def new
    @post = Post.find(params[:post_id])
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)

    @post = Post.find(params[:post_id])
    @photo.post = @post
    @photo.save
    redirect_to post_path(@post)
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
  end


  private

  def photo_params
    params.require(:photo).permit(:cloud_id)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def show
    @photo = Photo.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:post_id])
    @photo = Photo.find(params[:id])
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to @post, notice: 'Image has been deleted' }
      format.json { head :no_content }
      format.js   { render layout: false}
    end
  end


  private

  def photo_params
    params.require(:photo).permit(:cloud_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @photos = @post.photos.all
  end

  # GET /posts/new
  def new
    @post = Post.new
    @photos = @post.photos.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create

    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        if params[:photos]
          params[:photos].each do | photo |
            @post.photos.create(cloud_id: photo)
          end
        end

        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        if params[:photos]
          params[:photos].each do | photo |
            @post.photos.create(cloud_id: photo)
          end
        end

        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, photos_attributes: [:cloud_id, :post_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photoblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </body>
</html>

app/views/photo/new.html.erb
<h1>Add Photos to <%= @post.title %></h1>

<% simple_form_for [@post, @picture] do |f| %>

  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>

  <%= f.submit "add photo" %>
<% end %>

<%= link_to 'Back', post_path(@post) %>

app/views/photos/new.html.erb
<h1>Add Photos to <%= @post.title %></h1>

<%= simple_form_for [@post, @photo] do |f| %>

  <%= f.label :photo, "choose multiple photos" %>
  <%= f.file_field :cloud_id, multiple: true, name: "photos[]" %>

  <%= f.button :submit, "add photos" %>

<% end %>
<br>

<%= link_to 'Back', post_path(@post) %>

app/views/photos/show.html.erb
<div class="photo-container">
  <%= cl_image_tag(@photo.cloud_id, height: 500) %>
  <% if user_signed_in? %>
    <%= link_to 'Delete Photo', post_photo_path, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.input :title %>

    <%= f.input :description %>

    <%= f.fields_for :photo do |ff| %>
      <div class="field">
        <%= ff.label :photo %><br>
        <%= ff.file_field :cloud_id, multiple: true, name: "photos[]" %>
      </div>
    <% end %>

    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="home-banner index-banner">

  <h2>Photography portfolio</h2>

  <!-- scrool down button -->
  <section id="section04" class="demo">
    <a href=".card-container" data-scroll ><span></span>Scroll</a>
  </section>
</div>

<div class="card-container">
  <div class="cards">
    <% @posts.each do |post| %>
      <%= link_to post do %>
        <div class="card-category" style="background-image: url(<%= post.photos.first.cloud_id  %>)"><%= post.title %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Post', new_post_path %> |
  <%= button_to 'Exit', destroy_user_session_path, method: :delete %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="card-container">
  <div class="cards" >
    <% @photos.each do |photo|  %>
      <%= link_to cl_image_path(photo.cloud_id), "data-lightbox" => "gallery" do %>
        <div class="card-category" style="background-image: url(<%= photo.cloud_id  %>)">
        </div>
      <% end %>
    <% end %>
  </div>
</div>



<% if user_signed_in? %>
  <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %> |
<% end %>

app/views/posts/show_cards_as_images.html.erb
<div class="card-container">
  <div class="cards">
    <% @photos.each do |photo|  %>
        <div class="card-category">
          <%= cl_image_tag photo.cloud_id  %>
          <% if user_signed_in? %>
            <%= link_to '[X]', post_photo_path(@post, photo), method: :delete, data: { confirm: 'Are you sure?' } %> |
          <% end %>
        </div>
      <% end %>
  </div>
</div>

app/views/posts/show_temp.html.erb
<div class="home-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @photos.first.cloud_id  %>);">

  <h2><%= @post.title %></h2>

  <!-- scrool down button -->
  <section id="section04" class="demo">
    <a href=".card-container" data-scroll><span></span>Scroll</a>
  </section>
</div>



<div class="card-container">
  <div class="cards" >
    <% @photos.each do |photo|  %>
      <%= link_to cl_image_path(photo.cloud_id), "data-lightbox" => "gallery" do %>
        <div class="card-category" style="background-image: url(<%= photo.cloud_id  %>)">
        </div>
      <% end %>
    <% end %>
  </div>
</div>



<% if user_signed_in? %>
  <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %> |
<% end %>

app/views/shared/_footer.html.erb
<!-- footer -->
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/luisquilho/?hl=en" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://github.com/lquilho" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.linkedin.com/in/lu%C3%ADs-quilh%C3%B3-6230a5189/" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © All rights reserved
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">

  <%= link_to "LUÍS QUILHÓ", posts_path, class: "brand"%>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- space between here-->

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "HOME", posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "ABOUT", "about.html", class: "nav-link" %>
    </ul>
  </div>
</div>